autobots_sign_follower:
  ros__parameters:
    wall_stop_distance: 0.50
    forward_speed: 0.12
    rotate_speed: 0.8
    rotate_tolerance_deg: 3.0
    img_size: [128, 128]
    model_path: 'lab6-re/svm_rbf_v11.pkl'  # if empty, node will look for ../model_final.pkl
    confidence_threshold: 0.5
    use_odom_zeroing: true
